name: Test-build pull request
run-name: PR ${{ vars.PR_NUMBER }}
on:
  workflow_dispatch:

jobs:
  # Builds Trio
  build:
    name: Build
    runs-on: macos-15
    permissions:
      contents: write

    steps:
      - name: Select Xcode version
        run: "sudo xcode-select --switch /Applications/Xcode_16.3.app/Contents/Developer"
            
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: nightscout/Trio
          ref: dev
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
          fetch-depth: 1
          
      - name: Checkout pull request for building
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh pr checkout ${{ vars.PR_NUMBER }} --repo nightscout/Trio --recurse-submodules
          git submodule

      - name: Apply the optional repository variable `BUNDLE_ID_SUFFIX` to Config.xcconfig
        run: |
          CONFIG_FILE="Config.xcconfig"
          SUFFIX="${{ vars.BUNDLE_ID_SUFFIX }}"
          BASE="trio"

          if [[ -n "$SUFFIX" ]]; then
            BASE="${BASE}${SUFFIX}"
            BUNDLE_ID="org.nightscout.\$(DEVELOPMENT_TEAM).${BASE}"

            if grep -q "^BUNDLE_IDENTIFIER *=.*" "$CONFIG_FILE"; then
              sed -i '' "s|^BUNDLE_IDENTIFIER *=.*|BUNDLE_IDENTIFIER = ${BUNDLE_ID}|" "$CONFIG_FILE"
            else
              echo "BUNDLE_IDENTIFIER = ${BUNDLE_ID}" >> "$CONFIG_FILE"
            fi

            echo "Using BUNDLE_IDENTIFIER with suffix: $BUNDLE_ID"
          else
            echo "No BUNDLE_ID_SUFFIX set, using default bundle ID from Config.xcconfig:"
            grep "^BUNDLE_IDENTIFIER" "$CONFIG_FILE" || echo "(not set)"
          fi

      # Patch Fastlane Match to not print tables
      - name: Patch Match Tables
        run: find /usr/local/lib/ruby/gems -name table_printer.rb | xargs sed -i "" "/puts(Terminal::Table.new(params))/d"
      
      # Install project dependencies
      - name: Install project dependencies
        run: bundle install
      
      # Build signed Trio IPA file
      - name: Fastlane Build & Archive
        run: bundle exec fastlane build_trio
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      
      # Upload to TestFlight
      - name: Fastlane upload to TestFlight
        run: bundle exec fastlane release
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      # Upload Build artifacts
      - name: Upload build log, IPA and Symbol artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            artifacts
            buildlog
