name: Test-build pull request
run-name: PR ${{ vars.PR_NUMBER }}
on:
  workflow_dispatch:

jobs:
  # Builds Trio
  build:
    name: Build
    runs-on: macos-15
    permissions:
      contents: write

    steps:
      - name: Select Xcode version
        run: "sudo xcode-select --switch /Applications/Xcode_16.3.app/Contents/Developer"
            
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: nightscout/Trio
          ref: dev
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
          fetch-depth: 1
          
      - name: Checkout pull request for building
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh pr checkout ${{ vars.PR_NUMBER }} --repo nightscout/Trio --recurse-submodules
          git submodule

      - name: Patch Config.xcconfig with bundle ID and team ID
        run: |
          CONFIG_FILE="Config.xcconfig"

          # Variables from GitHub context
          TEAM_ID="${{ secrets.TEAMID }}"
          SUFFIX="${{ vars.BUNDLE_ID_SUFFIX }}"
          BASE="trio"
          [[ -n "$SUFFIX" ]] && BASE="${BASE}${SUFFIX}"
          BUNDLE_ID="org.nightscout.${TEAM_ID}.${BASE}"

          # Function to replace or insert key-value pairs in .xcconfig
          update_xcconfig_key() {
            local key="$1"
            local value="$2"
            local file="$3"

            if grep -q "^${key} *=.*" "$file"; then
              sed -i '' "s|^${key} *=.*|${key} = ${value}|" "$file"
            else
              echo "${key} = ${value}" >> "$file"
            fi
          }

          echo "--- Before update ---"
          cat "$CONFIG_FILE"

          update_xcconfig_key "DEVELOPER_TEAM" "$TEAM_ID" "$CONFIG_FILE"
          update_xcconfig_key "BUNDLE_IDENTIFIER" "$BUNDLE_ID" "$CONFIG_FILE"

          echo "--- After update ---"
          cat "$CONFIG_FILE"

      # Patch Fastlane Match to not print tables
      - name: Patch Match Tables
        run: find /usr/local/lib/ruby/gems -name table_printer.rb | xargs sed -i "" "/puts(Terminal::Table.new(params))/d"
      
      # Install project dependencies
      - name: Install project dependencies
        run: bundle install
      
      # Build signed Trio IPA file
      - name: Fastlane Build & Archive
        run: bundle exec fastlane build_trio
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      
      # Upload to TestFlight
      - name: Fastlane upload to TestFlight
        run: bundle exec fastlane release
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      # Upload Build artifacts
      - name: Upload build log, IPA and Symbol artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            artifacts
            buildlog
