name: Sync with nightscout/Trio dev (ff or merge)

on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 3 * * *'  # Daily at 03:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current branch name
        id: branch
        run: echo "branch_name=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT

      - name: Add upstream and fetch dev
        run: |
          git remote add upstream https://github.com/nightscout/Trio.git
          git fetch upstream dev

      - name: Set git user for merge commits
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Attempt fast-forward merge
        id: ff_merge
        continue-on-error: true
        run: |
          git checkout ${{ steps.branch.outputs.branch_name }}
          git merge --ff-only upstream/dev

      - name: Fallback to regular merge if ff-only failed
        if: steps.ff_merge.outcome == 'failure'
        run: |
          echo "Fast-forward failed, doing regular merge."
          git merge upstream/dev

      - name: Push changes
        run: |
          git push origin ${{ steps.branch.outputs.branch_name }}
