name: Sync with nightscout/Trio dev (ff-only)

on:
  workflow_dispatch:        # Manually triggerable
  #schedule:
    #- cron: '0 3 * * *'     # Runs daily at 03:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Full history needed for merging

      - name: Get current branch name
        id: branch
        run: echo "branch_name=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/nightscout/Trio.git
          git fetch upstream

      - name: Attempt fast-forward merge from upstream/dev
        run: |
          git checkout ${{ steps.branch.outputs.branch_name }}
          git merge --ff-only upstream/dev

      - name: Push changes if merge succeeded
        run: |
          git push origin ${{ steps.branch.outputs.branch_name }}
